apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-rep
spec:
  replicas: 10
  selector:
    app: selenium-chrome
  template:
    metadata:
      name: selenium-chrome
      labels:
        app: selenium-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: node-chrome
          image: selenium/node-chrome-debug:3.141
          ports:
            - containerPort: 5555
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          env:
            - name: HUB_HOST
              value: "selenium-srv"
            - name: HUB_PORT
              value: "4444"
